import type { ConnectionCheck, Project } from '../api'

export function ProjectDrawer({ open, projects, onClose, onOpen }: { open: boolean; projects: Project[]; onClose: () => void; onOpen: (id: string) => void }) {
  if (!open) return null
  return <div className="overlay" onMouseDown={onClose}><aside className="drawer" onMouseDown={(event) => event.stopPropagation()}><header><div><span className="eyebrow">项目</span><h2>历史项目</h2></div><button className="close-button" onClick={onClose}>关闭</button></header><div className="project-list">{projects.length ? projects.map((project) => <button key={project.id} onClick={() => onOpen(project.id)}><strong>{project.reference_video_name?.replace(/\.[^.]+$/, '') || project.name}</strong><small>{project.reference_video_name || project.name}</small></button>) : <p className="empty-list">当前页面还没有历史项目。</p>}</div></aside></div>
}

export function SettingsDialog({ open, preflight, checks, volcengineKey, comflyKey, onClose, onPreflight, onTest, onVolcengineKey, onComflyKey, onSaveVolcengine, onSaveComfly }: { open: boolean; preflight: Record<string, { ready: boolean; model: string; endpoint: string }> | null; checks: Record<string, ConnectionCheck>; volcengineKey: string; comflyKey: string; onClose: () => void; onPreflight: () => void; onTest: (service: string) => void; onVolcengineKey: (value: string) => void; onComflyKey: (value: string) => void; onSaveVolcengine: () => void; onSaveComfly: () => void }) {
  if (!open) return null
  const labels: Record<string, string> = { volcengine_generation: '官方 Seedance', comfly_generation: 'Comfly Seedance', comfly_prompt: 'Comfly GPT', storyboard_vision: '分镜视觉理解', temporary_publisher: '临时素材发布' }
  const result = (service: string) => checks[service] && <small className={checks[service].connected ? 'connection-ok' : 'connection-error'}>{checks[service].message}</small>
  return <div className="overlay" onMouseDown={onClose}><section className="settings-dialog" onMouseDown={(event) => event.stopPropagation()}><header><div><span className="eyebrow">仅保存到本机服务器</span><h2>服务与凭证</h2><p>逐镜理解需要火山方舟 Key 与 Comfly Key 同时可用。</p></div><button className="close-button" onClick={onClose}>关闭</button></header><div className="settings-groups"><section className="settings-group"><div className="settings-group-heading"><span>01</span><div><h3>双模型理解</h3><p>豆包读取完整镜头片段，GPT读取连续关键帧并生成最终分镜事实。</p></div></div><div className="settings-grid"><article><strong>火山方舟</strong><small>用于豆包完整镜头理解</small><label>方舟 API Key<input type="password" autoComplete="new-password" placeholder="Bearer API Key" value={volcengineKey} onChange={(event) => onVolcengineKey(event.target.value)} /></label><div><button className="button secondary" disabled={!volcengineKey.trim()} onClick={onSaveVolcengine}>保存并测试</button>{preflight?.volcengine_generation.ready && <button className="button ghost" onClick={() => onTest('volcengine_generation')}>重新测试</button>}</div>{result('volcengine_generation')}</article><article><strong>Comfly</strong><small>用于GPT关键帧理解、综合事实和最终提示词</small><label>Comfly API Key<input type="password" autoComplete="new-password" value={comflyKey} onChange={(event) => onComflyKey(event.target.value)} /></label><div><button className="button secondary" disabled={!comflyKey.trim()} onClick={onSaveComfly}>保存并测试</button>{preflight?.comfly_prompt.ready && <button className="button ghost" onClick={() => onTest('comfly_prompt')}>重新测试</button>}</div>{result('comfly_prompt')}</article></div></section><section className="settings-group"><div className="settings-group-heading"><span>02</span><div><h3>分镜视觉理解</h3><p>人工确认边界后，本地裁切镜头；豆包所需片段会临时发布约24小时，GPT只接收本地抽取的带时间戳关键帧。</p></div></div><div className="preflight-list"><span className={preflight?.storyboard_vision.ready ? 'ready' : ''}><i />{preflight?.storyboard_vision.ready ? `已就绪：${preflight.storyboard_vision.model}` : '请同时配置火山方舟与 Comfly API Key'}</span></div></section></div><footer><button className="button ghost" onClick={onPreflight}>刷新配置状态</button>{preflight && <div className="preflight-list">{Object.entries(preflight).map(([key, item]) => <span key={key} className={item.ready ? 'ready' : ''}><i />{labels[key] || key}：{item.ready ? '已配置' : '未配置'}</span>)}</div>}<small>密钥仅写入本机后端 .env。保存后立即生效，不需要重启后端。</small></footer></section></div>
}
