import type { ConnectionCheck, Project } from '../api'
import { useState } from 'react'

export function ProjectDrawer({ open, projects, deletingId, onClose, onOpen, onDelete, onRename }: { open: boolean; projects: Project[]; deletingId: string | null; onClose: () => void; onOpen: (id: string) => void; onDelete: (id: string, name: string) => void; onRename: (id: string, name: string) => Promise<void> | void }) {
  const [editingId, setEditingId] = useState<string | null>(null)
  const [draft, setDraft] = useState('')
  const [saving, setSaving] = useState(false)
  if (!open) return null
  return <div className="overlay" onMouseDown={onClose}><aside className="drawer" onMouseDown={(event) => event.stopPropagation()}><header><div><span className="eyebrow">项目</span><h2>历史项目</h2></div><button className="close-button" onClick={onClose}>关闭</button></header><div className="project-list">{projects.length ? projects.map((project) => editingId === project.id ? <form className="project-rename" key={project.id} onSubmit={async (event) => { event.preventDefault(); const name = draft.trim(); if (!name) return; setSaving(true); try { await onRename(project.id, name); setEditingId(null) } finally { setSaving(false) } }}><input autoFocus maxLength={200} value={draft} onChange={(event) => setDraft(event.target.value)} aria-label={`项目名称 ${project.name}`} /><button type="submit" disabled={saving || !draft.trim()}>{saving ? '保存中' : '保存'}</button><button type="button" onClick={() => setEditingId(null)}>取消</button></form> : <div className="project-list-item" key={project.id}><button className="project-open" onClick={() => onOpen(project.id)}><strong>{project.name}</strong><small>{project.reference_video_name || '尚未上传参考视频'}</small></button><button className="project-rename-button" onClick={() => { setEditingId(project.id); setDraft(project.name) }}>重命名</button><button className="project-delete" disabled={deletingId === project.id} onClick={() => onDelete(project.id, project.name)} aria-label={`删除项目 ${project.name}`}>{deletingId === project.id ? '删除中' : '删除'}</button></div>) : <p className="empty-list">当前页面还没有历史项目。</p>}</div></aside></div>
}

export function SettingsDialog({ open, preflight, checks, volcengineKey, comflyKey, onClose, onPreflight, onTest, onVolcengineKey, onComflyKey, onSaveVolcengine, onSaveComfly }: { open: boolean; preflight: Record<string, { ready: boolean; model: string; endpoint: string }> | null; checks: Record<string, ConnectionCheck>; volcengineKey: string; comflyKey: string; onClose: () => void; onPreflight: () => void; onTest: (service: string) => void; onVolcengineKey: (value: string) => void; onComflyKey: (value: string) => void; onSaveVolcengine: () => void; onSaveComfly: () => void }) {
  if (!open) return null
  const labels: Record<string, string> = { volcengine_generation: '官方 Seedance', comfly_generation: 'Comfly Seedance', comfly_prompt: 'Comfly AI', storyboard_vision: '分镜视觉理解', temporary_publisher: '临时素材发布' }
  const result = (service: string) => checks[service] && <small className={checks[service].connected ? 'connection-ok' : 'connection-error'}>{checks[service].message}</small>
  return <div className="overlay" onMouseDown={onClose}><section className="settings-dialog" onMouseDown={(event) => event.stopPropagation()}><header><div><span className="eyebrow">仅保存到本机服务器</span><h2>服务与凭证</h2><p>逐镜理解只需要 Comfly Key；火山方舟 Key 仅用于官方 Seedance 视频生成。</p></div><button className="close-button" onClick={onClose}>关闭</button></header><div className="settings-groups"><section className="settings-group"><div className="settings-group-heading"><span>01</span><div><h3>模型与生成服务</h3><p>Qwen读取完整镜头并直接生成最终分镜事实；GPT不再参与逐镜理解。</p></div></div><div className="settings-grid"><article><strong>火山方舟</strong><small>仅用于官方 Seedance 视频生成</small><label>方舟 API Key<input type="password" autoComplete="new-password" placeholder="Bearer API Key" value={volcengineKey} onChange={(event) => onVolcengineKey(event.target.value)} /></label><div><button className="button secondary" disabled={!volcengineKey.trim()} onClick={onSaveVolcengine}>保存并测试</button>{preflight?.volcengine_generation.ready && <button className="button ghost" onClick={() => onTest('volcengine_generation')}>重新测试</button>}</div>{result('volcengine_generation')}</article><article><strong>Comfly</strong><small>用于Qwen逐镜理解、GPT参考图档案与提示词整理、Comfly Seedance</small><label>Comfly API Key<input type="password" autoComplete="new-password" value={comflyKey} onChange={(event) => onComflyKey(event.target.value)} /></label><div><button className="button secondary" disabled={!comflyKey.trim()} onClick={onSaveComfly}>保存并测试</button>{preflight?.comfly_prompt.ready && <button className="button ghost" onClick={() => onTest('comfly_prompt')}>重新测试</button>}</div>{result('comfly_prompt')}</article></div></section><section className="settings-group"><div className="settings-group-heading"><span>02</span><div><h3>分镜视觉理解</h3><p>Qwen接收完整镜头；过短镜头使用相同码流无损循环到3秒，只分析第一轮动作。</p></div></div><div className="preflight-list"><span className={preflight?.storyboard_vision.ready ? 'ready' : ''}><i />{preflight?.storyboard_vision.ready ? `已就绪：${preflight.storyboard_vision.model}` : '请配置 Comfly API Key'}</span></div></section></div><footer><button className="button ghost" onClick={onPreflight}>刷新配置状态</button>{preflight && <div className="preflight-list">{Object.entries(preflight).map(([key, item]) => <span key={key} className={item.ready ? 'ready' : ''}><i />{labels[key] || key}：{item.ready ? '已配置' : '未配置'}</span>)}</div>}<small>密钥仅写入本机后端 .env。保存后立即生效，不需要重启后端。</small></footer></section></div>
}
