import { useState } from 'react'
import type { ChangeEvent, RefObject } from 'react'
import { inferProductProfile } from './productProfile'
import './visionSetup.css'
import './timelineEditor.css'

type Shot = { id: string; start: number; end: number; label: string; people?: string | null; action?: string | null; productInteraction?: string | null; background?: string | null; camera?: string | null; lighting?: string | null; observations?: string | null; uncertainties?: string | null; evidence?: Array<{ timestamp_sec: number; image_url: string }>; edit?: { people: string; background: string; action: string; camera: string; keep_unchanged: string[] } | null }
type Edit = { people: string; background: string; action: string; camera: string; keep: string }

export type StudioProps = {
  fileName: string; videoUrl: string; videoRatio: string; videoRef: RefObject<HTMLVideoElement | null>; shots: Shot[]; selectedShot: string
  notice: string; analyzing: boolean; productImageName: string; productAnalysisStatus: string; productProfile: string; prompt: string; promptVersion: number; provider: 'volcengine' | 'comfly'; audioMode: 'keep' | 'style'; audioStyle: string; shotEdit: Edit; generatedVideoUrl: string; visionSetupRequired: boolean; visionSettings: { accessKey: string; secretKey: string; space: string }
  onVideo: (event: ChangeEvent<HTMLInputElement>) => void; onProductImage: (event: ChangeEvent<HTMLInputElement>) => void; onAnalyze: () => void; onSelect: (shot: Shot) => void; onSplit: (atSec?: number) => void; onBoundary: (leftIndex: number, atSec: number) => void; onMerge: () => void; onSaveTimeline: () => void; onEdit: (edit: Edit) => void; onSaveShot: () => void; onProduct: (value: string) => void; onPrompt: (value: string) => void; onProvider: (value: 'volcengine' | 'comfly') => void; onAudioMode: (value: 'keep' | 'style') => void; onAudioStyle: (value: string) => void; onSavePrompt: () => void; onGenerate: () => void; onRefresh: () => void; onVideoMetadata: (width: number, height: number) => void; mediaUrl: (url: string) => string; onVisionSettings: (value: { accessKey: string; secretKey: string; space: string }) => void; onSaveVisionSettings: () => void
}

function Fact({ label, value }: { label: string; value?: string | null }) { return <div><span>{label}</span><p>{value || '待 AI 确认'}</p></div> }

export function StudioView(p: StudioProps) {
  const shot = p.shots.find((item) => item.id === p.selectedShot)
  const [playhead, setPlayhead] = useState(0)
  const duration = p.shots.at(-1)?.end || 0
  const shotIndex = p.shots.findIndex((item) => item.id === p.selectedShot)
  const adjustableBoundary = shotIndex >= 0 && shotIndex < p.shots.length - 1 ? p.shots[shotIndex].end : null
  return <main className="studio-shell">
    <header className="studio-top"><div className="studio-brand"><b>AD</b><span>Seedance 广告工作台</span></div><button className="quiet-button">历史项目</button></header>
    <section className="studio-heading"><div><span>参考广告改编</span><h1>{p.fileName || '创建一条产品广告'}</h1><p>AI 先理解产品图和每个视频镜头，你再决定保留和修改的部分。</p></div><div className="heading-assets"><label className="quiet-button file-button">{p.productImageName || '上传产品图'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={p.onProductImage} /></label><label className="quiet-button file-button">{p.fileName ? '替换视频' : '选择视频'}<input type="file" accept="video/*" onChange={p.onVideo} /></label><small>{p.productAnalysisStatus === 'processing' ? 'AI 正在理解产品图' : p.productAnalysisStatus === 'completed' ? '产品档案已生成' : p.productAnalysisStatus === 'failed' ? '产品图已保存，理解未完成' : '产品图会先转成文字档案'}</small></div></section>
    <nav className="process"><span className={p.fileName ? 'done' : 'active'}><b>1</b>上传素材</span><span className={p.shots.length ? 'done' : p.fileName ? 'active' : ''}><b>2</b>理解视频</span><span className={p.shots.length ? 'active' : ''}><b>3</b>修改镜头</span><span><b>4</b>确认产品</span><span><b>5</b>生成广告</span></nav>
    {!p.fileName ? <section className="drop-zone"><span>01</span><h2>上传参考视频</h2><p>支持 MP4、MOV、WebM，建议 30 秒以内。</p><label className="main-button file-button">选择视频<input type="file" accept="video/*" onChange={p.onVideo} /></label></section> : <>
      {adjustableBoundary !== null && <div className="single-boundary"><div className="single-boundary-head"><b>调整镜头 {shotIndex + 1} 和 {shotIndex + 2} 的边界</b><span>{adjustableBoundary.toFixed(2)} 秒</span></div><input type="range" min={p.shots[shotIndex].start + 0.04} max={p.shots[shotIndex + 1].end - 0.04} step="0.04" value={adjustableBoundary} onChange={(e) => p.onBoundary(shotIndex, Number(e.target.value))} /><div className="frame-buttons"><button onClick={() => p.onBoundary(shotIndex, adjustableBoundary - 0.04)}>前移 1 帧</button><button onClick={() => p.onBoundary(shotIndex, adjustableBoundary + 0.04)}>后移 1 帧</button></div></div>}
      <section className="studio-grid">
        <aside className="shot-column"><div className="column-head"><div><span>镜头列表</span><h2>{p.shots.length ? `${p.shots.length} 个镜头` : '尚未分析'}</h2></div><button onClick={p.onAnalyze} disabled={p.analyzing}>{p.analyzing ? '分析中…' : p.shots.length ? '重新理解' : '开始理解'}</button></div>{p.shots.length ? <div className="shot-list">{p.shots.map((item, index) => <button className={item.id === p.selectedShot ? 'active' : ''} key={item.id} onClick={() => p.onSelect(item)}><strong>{String(index + 1).padStart(2, '0')}</strong><span><b>{item.action || item.productInteraction || `镜头 ${index + 1}`}</b><small>{item.start.toFixed(1)} — {item.end.toFixed(1)} 秒</small></span><i>{item.edit ? '已修改' : item.observations ? '已理解' : p.analyzing ? '理解中' : '待运行理解'}</i></button>)}</div> : <div className="empty-column"><h3>先让 AI 理解视频</h3><p>系统会自动完成切点、关键帧和逐镜内容分析。</p><button className="main-button" onClick={p.onAnalyze}>{p.analyzing ? '正在启动…' : '开始理解视频'}</button></div>}<div className="mini-tools"><button onClick={() => p.onSplit(playhead)}>在 {playhead.toFixed(2)}s 拆分</button><button onClick={p.onMerge}>合并</button><button onClick={p.onSaveTimeline}>保存时间轴</button></div></aside>
        <section className="preview-column"><div className="column-head"><div><span>当前画面</span><h2>{shot ? `${shot.start.toFixed(1)} — ${shot.end.toFixed(1)} 秒` : p.fileName}</h2></div></div><div className="studio-video" style={{ aspectRatio: p.videoRatio }}><video ref={p.videoRef} controls src={p.videoUrl} onTimeUpdate={(e) => setPlayhead(e.currentTarget.currentTime)} onLoadedMetadata={(e) => p.onVideoMetadata(e.currentTarget.videoWidth, e.currentTarget.videoHeight)} /></div>{duration > 0 && <div className="boundary-editor"><div className="timeline-track">{p.shots.map((item,index) => <button key={item.id} className={item.id === p.selectedShot ? 'active' : ''} style={{width:`${((item.end-item.start)/duration)*100}%`}} onClick={() => p.onSelect(item)}>{index+1}</button>)}</div><input className="playhead" aria-label="播放位置" type="range" min="0" max={duration} step="0.04" value={playhead} onChange={(e) => {const value=Number(e.target.value);setPlayhead(value);if(p.videoRef.current)p.videoRef.current.currentTime=value}} />{p.shots.slice(0,-1).map((item,index) => <label key={item.id} className="boundary-handle" style={{left:`${(item.end/duration)*100}%`}}><span>{item.end.toFixed(2)}s</span><input aria-label={`镜头 ${index+1} 和 ${index+2} 的边界`} type="range" min={item.start+0.04} max={p.shots[index+1].end-0.04} step="0.04" value={item.end} onChange={(e) => p.onBoundary(index,Number(e.target.value))} /></label>)}</div>}{shot?.evidence?.length ? <div className="studio-evidence">{shot.evidence.map((item) => <img key={item.image_url} src={p.mediaUrl(item.image_url)} alt={`${item.timestamp_sec} 秒证据帧`} />)}</div> : <p className="preview-note">理解完成后，这里会显示当前镜头的证据帧。</p>}</section>
        <aside className="edit-column"><div className="column-head"><div><span>AI 理解</span><h2>{shot?.label || '选择一个镜头'}</h2></div></div>{shot ? <><div className="fact-list"><Fact label="人物" value={shot.people} /><Fact label="动作" value={shot.action} /><Fact label="产品互动" value={shot.productInteraction} /><Fact label="背景" value={shot.background} /><Fact label="运镜" value={shot.camera} /><Fact label="光线" value={shot.lighting} /></div>{shot.uncertainties && <div className="warning"><b>需要你确认</b>{shot.uncertainties}</div>}<div className="edit-fields"><h3>我要修改</h3>{(['people','background','action','camera'] as const).map((key) => <label key={key}>{{people:'人物',background:'背景',action:'动作',camera:'运镜'}[key]}<input value={p.shotEdit[key]} placeholder="不填则保持原样" onChange={(e) => p.onEdit({...p.shotEdit,[key]:e.target.value})} /></label>)}<label>必须保持不变<textarea value={p.shotEdit.keep} placeholder="例：产品外形、Logo" onChange={(e) => p.onEdit({...p.shotEdit,keep:e.target.value})} /></label><button className="main-button" onClick={p.onSaveShot}>确认这个镜头</button></div></> : <p className="preview-note">分析完成后在左侧选择镜头。</p>}</aside>
      </section>
      <section className="output-grid"><div><span className="section-label">04 · 产品锁定</span><h2>确认原产品事实</h2><p>AI 仅提供初稿，请人工确认外形、包装、Logo、文字和使用动作。</p><textarea value={p.productProfile || inferProductProfile(p.shots)} onChange={(e) => p.onProduct(e.target.value)} /></div><div><div className="output-head"><div><span className="section-label">05 · 生成广告</span><h2>完整分镜提示词</h2></div><small>{p.promptVersion ? `已保存 v${p.promptVersion}` : '草稿'}</small></div><textarea className="prompt-output" value={p.prompt} onChange={(e) => p.onPrompt(e.target.value)} /><div className="generation-row"><label><input type="radio" checked={p.provider === 'volcengine'} onChange={() => p.onProvider('volcengine')} />火山官方</label><label><input type="radio" checked={p.provider === 'comfly'} onChange={() => p.onProvider('comfly')} />Comfly</label><label><input type="radio" checked={p.audioMode === 'keep'} onChange={() => p.onAudioMode('keep')} />保持原 BGM</label><label><input type="radio" checked={p.audioMode === 'style'} onChange={() => p.onAudioMode('style')} />新音频风格</label></div>{p.audioMode === 'style' && <input value={p.audioStyle} onChange={(e) => p.onAudioStyle(e.target.value)} />}<div className="output-actions"><button className="quiet-button" onClick={p.onSavePrompt}>保存版本</button><button className="main-button" onClick={p.onGenerate}>生成广告视频</button></div>{p.generatedVideoUrl && <video className="result-video" controls src={p.generatedVideoUrl} />}<button className="refresh-link" onClick={p.onRefresh}>刷新生成状态</button></div></section>
    </>}
    {p.visionSetupRequired && <section className="vision-setup"><div><span className="section-label">需要配置</span><h2>连接火山 VOD 视频理解</h2><p>Seedance API Key 只负责生成视频。理解参考视频另外需要 VOD 的 Access Key、Secret Key 和 Space 名称。凭证只保存在你的服务器。</p></div><div className="vision-fields"><label>Access Key<input type="password" value={p.visionSettings.accessKey} onChange={(e) => p.onVisionSettings({...p.visionSettings,accessKey:e.target.value})} /></label><label>Secret Key<input type="password" value={p.visionSettings.secretKey} onChange={(e) => p.onVisionSettings({...p.visionSettings,secretKey:e.target.value})} /></label><label>VOD Space<input value={p.visionSettings.space} onChange={(e) => p.onVisionSettings({...p.visionSettings,space:e.target.value})} /></label><button className="main-button" onClick={p.onSaveVisionSettings}>保存视频理解配置</button></div></section>}
    <div className="studio-notice"><i />{p.notice}</div>
  </main>
}
